Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.userPoolName}
      AutoVerifiedAttributes:
        - phone_number
      MfaConfiguration: "OFF"
      AliasAttributes:
        - phone_number
      SmsConfiguration:
        ExternalId: ${self:service.name}-${self:provider.stage}-external
        SnsCallerArn: !GetAtt SnsRole.Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: true
          Required: false
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - CognitoUserPoolIdentityProviderAmazon
      - CognitoUserPoolIdentityProviderGoogle
      - CognitoUserPoolIdentityProviderFacebook
    Properties:
      ClientName: ${self:service.name}-${self:provider.stage}-user-pool-client
      GenerateSecret: false
      SupportedIdentityProviders:
        - Google
        - Facebook
        - LoginWithAmazon
        - COGNITO
      CallbackURLs:
        - ${env:CALLBACK_URL}
      LogoutURLs:
        - ${env:LOGOUT_URL}
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - aws.cognito.signin.user.admin
        - profile
        - phone
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_CUSTOM_AUTH
      AllowedOAuthFlowsUserPoolClient: true
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: ${self:service.name}-${self:provider.stage}
      UserPoolId: !Ref CognitoUserPool
Outputs:
  UserPoolId:
    Description: The Id of the CognitoUserPool
    Value: !Ref CognitoUserPool