Resources:
  WednesdayERP:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: employeeId
          AttributeType: S
        - AttributeName: officeId
          AttributeType: S
        - AttributeName: countryStateCity
          AttributeType: S
      TableName: 'WednesdayERP-${self:service.name}-${self:provider.stage}'
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: officeId
          KeySchema:
            - AttributeName: officeId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - officeName
              - address
              - countryStateCity
            ProjectionType: INCLUDE
        - IndexName: employeeId
          KeySchema:
            - AttributeName: employeeId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - employeeName
            ProjectionType: INCLUDE
        - IndexName: address
          KeySchema:
            - AttributeName: countryStateCity
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - officeId
              - officeName
              - address
            ProjectionType: INCLUDE
