Resources:
  WednesdayERP:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      TableName: 'MultiTenantERP-${self:service.name}-${self:provider.stage}'
      BillingMode: PAY_PER_REQUEST
