service:
  name: ${env:NAME}
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  versionFunctions: false
package:
  individually: true
custom:
  userPoolName: ${env:NAME}-${env:STAGE}-user-pool
  webpack:
    includeModules: true
    excludeFiles: ./**/*.test.js
functions:
  - createAuthChallenge:
      handler: functions/cognito-triggers/create-auth-challenge/index.handler
      role: LambdaSnsRole
      dependsOn:
        - CognitoUserPool
        - LambdaSnsRole
      events:
        - cognitoUserPool:
            trigger: CreateAuthChallenge
            pool: ${self:custom.userPoolName}
            existing: true
  - verifyAuthChallenge:
      handler: functions/cognito-triggers/verify-auth-challenge/index.handler
      dependsOn:
        - CognitoUserPool
      events:
        - cognitoUserPool:
            trigger: VerifyAuthChallengeResponse
            pool: ${self:custom.userPoolName}
            existing: true
  - defineAuthChallenge:
      handler: functions/cognito-triggers/define-auth-challenge/index.handler
      dependsOn:
        - CognitoUserPool
      events:
        - cognitoUserPool:
            trigger: DefineAuthChallenge
            pool: ${self:custom.userPoolName}
            existing: true
resources:
  - ${file(./resources/cognito-identity-providers.yml)}
  - ${file(./resources/cognito.yml)}
  - ${file(./resources/roles-and-policies.yml)}
